### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by stampylongr** [WarlockD/GMdsam#21]
I ran the decompiler with the latest version of UNDERTALE, and this happened:
```cmd
Unhandled Exception: System.Exception: Expected bool to be 0 or 1
   at GameMaker.BinaryReaderExtensions.ReadIntBool(BinaryReader r)
   at GameMaker.File.Room.Background.InternalRead(BinaryReader r)
   at GameMaker.File.GameMakerStructure.Read(BinaryReader r, Int32 index)
   at GameMaker.File.GameMakerStructure.ArrayFromOffset[T](BinaryReader r)
   at GameMaker.File.GameMakerStructure.ArrayFromOffset[T](BinaryReader r, Int32 offset)
   at GameMaker.File.Room.InternalRead(BinaryReader r)
   at GameMaker.File.GameMakerStructure.Read(BinaryReader r, Int32 index)
   at GameMaker.File.ReadList[T](List`1 list, BinaryReader r, Int32 start, Int32 end)
   at GameMaker.File.CheckList[T](String chunkName, List`1& list)
   at GameMaker.File.LoadEveything()
   at GameMaker.Program.Main(String[] args)
```

**Comment by stampylongr** [comment]
Could this be because it was (possibly) made in GMS2? I know you can import old GMS projects into GMS2.

**Comment by Kneesnap** [comment]
Yes. This tool is for an old version of GMS1. There could easily be changes since then.
